import { SourceLink } from "./SourceLink";
import { sources } from "@/data/sources";
import { priceCheck } from "@/data/flightPrices";

export function FlightBrief() {
  return <section className="editorial-section flight-brief" id="repules"><div className="section-kicker">Repülési alapok · árak lekérdezve {priceCheck.checkedOn}</div><h2>Két közvetlen kapu van – és nem ott, ahol vártuk</h2><div className="flight-grid">
    <article className="recommended"><span className="badge">AJÁNLOTT MEGOLDÁS</span><span className="airport">SZX</span><h3>Budapest ↔ Shenzhen, oda-vissza</h3><p>Hainan HU 762 (11:50 → 04:50+1, 11 óra) és HU 761 (01:55 → 07:15, 12 óra 20 perc), hétfőn és pénteken. Okt. 16. péntek és okt. 30. péntek is jó nap. <strong>3 016 € négy főre</strong>, mindkét irány közvetlen, fejenként egy feladott bőrönddel.</p><SourceLink source={sources.flightSZXBUD} /></article>
    <article><span className="airport">CAN</span><h3>Guangzhou → Budapest</h3><p>A China Southern CZ 649 valóban létezik: kedd, csütörtök és szombat, 01:30-kor indul, 12 óra 40 perc. Egyirányú jegyként <strong>1 689 €</strong> négy főre. A csapda: a Hainan odaúttal <em>nem</em> kombinálható egyetlen nyitott szárú jegyre – egy jegyen kérve 26,5 órás, kétátszállásos hazautat kapunk.</p><SourceLink source={sources.flightCANBUD} /></article>
    <article><span className="airport">HKG</span><h3>Hongkong → Budapest</h3><p>Nincs közvetlen járat – ezt október 29-re és 30-ra is ellenőriztük. Istanbul, Doha vagy Dubaj felé egy átszállással jellemzően 15–19 óra. HKG akkor jó végpont, ha nem megyünk tovább nyugatra.</p><SourceLink source={{ label: "HKG hivatalos járatkereső", url: "https://www.hongkongairport.com/en/flights/airlines-information/airlines.page" }} /></article>
    <article><span className="airport">HAN</span><h3>Hanoi → Budapest</h3><p>Egyátszállásos utak Doha, Dubaj és Istanbul felé; a legolcsóbb a Qatar <strong>1 336 €</strong>-ért, 13 óra 5 perc alatt. Ez jobb, mint visszarepülni Kínába egy közvetlen BUD-járatért – de az odautat így is érdemes közvetlen shenzheni jeggyel megvenni.</p><SourceLink source={sources.flightHANBUD} /></article>
  </div><div className="notice"><strong>Az árak konkrétak, nem becslések.</strong> Google Flights, {priceCheck.checkedOn}, {priceCheck.passengers}, {priceCheck.cabin}, a foglalási panelig végigkattintva; minden összeg a teljes négyfős társaságra, adókkal. A teljes összevetés – útvonalanként, regionális szakaszokkal és menetrendi napokkal – a <a href="./repuloarak/"><strong>repülőárak oldalon</strong></a> van. A kínai vasúti jegyek rövid értékesítési ablaka miatt az októberi konkrét vonatjegyek augusztusban még nem foglalhatók.</div></section>;
}
