import { SourceLink } from "./SourceLink";
import { sources } from "@/data/sources";
import { decision, grouped, priceCheck } from "@/data/flightPrices";

export function FlightBrief() {
  return <section className="editorial-section flight-brief" id="repules"><div className="section-kicker">A megvett keret · árak lekérdezve {priceCheck.checkedOn}</div><h2>Shenzhen oda-vissza, közvetlenül</h2><div className="flight-grid">
    <article className="recommended"><span className="badge">EZ VAN MEGVÉVE</span><span className="airport">SZX</span><h3>Budapest ↔ Shenzhen</h3><p>Hainan HU 762 okt. 16-án 11:50 → 04:50+1 (11 óra), és HU 761 okt. 30-án 01:55 → 07:15 (12 óra 20 perc). <strong>{grouped(decision.price)} € négy főre</strong>, mindkét irány közvetlen, {decision.baggage}. Marad {decision.ground}.</p><SourceLink source={sources.flightSZXBUD} /></article>
    <article><span className="airport">🚆</span><h3>Ami vonattal elérhető</h3><p>Hongkong 14–33 perc, Guangzhou 30–75 perc, Zhaoqing 1,5–2,5 óra, Chaozhou 1:28–3:14, Guilin/Yangshuo kb. 3–3,5 óra, Xiamen 2,5–4 óra. Mind közvetlen, mind visszafordítható – ezekre épül a hét útvonal többsége.</p><SourceLink source={sources.railSZHK} /></article>
    <article><span className="airport">🏖️</span><h3>Ami a fürdést adja</h3><p>Dapeng-félsziget kb. 2 óra közúton Shenzhentől (Xichong, Dongchong), Hongkongnak saját öblei vannak (Big Wave Bay, Cheung Sha, Sai Kung). Ha trópusi tenger kell: Sanya Hongkongból 1 óra 45 perc közvetlen, oda-vissza 524 € négy főre.</p><SourceLink source={sources.flightHKGSanya} /></article>
    <article><span className="airport">✈️</span><h3>Repülős kitérők – oda-vissza</h3><p>Mivel Shenzhenből megyünk haza, minden repülős kitérő oda-vissza jegy: Sanya 524 € (Hongkongból), Hanoi/Ninh Binh 935 € (Shenzhenből) vagy 970 € (Hongkongból), Xi’an egy irányba 271 € Shenzhenből. Angkor és Zhangjiajie repülővel nem éri meg.</p><SourceLink source={sources.flightSZXHAN} /></article>
  </div><div className="notice"><strong>Az árak konkrétak, nem becslések.</strong> Google Flights, {priceCheck.checkedOn} és {priceCheck.regionalCheckedOn}, {priceCheck.passengers}, {priceCheck.cabin}, a foglalási panelig végigkattintva; minden összeg a teljes négyfős társaságra, adókkal. A teljes összevetés a <a href="./repuloarak/"><strong>repülőárak oldalon</strong></a> van. A kínai vasúti jegyek rövid értékesítési ablaka miatt az októberi konkrét vonatjegyek augusztusban még nem foglalhatók.</div></section>;
}
