import { SourceLink } from "./SourceLink";
import { sources } from "@/data/sources";
import { grouped, priceCheck } from "@/data/flightPrices";

export function FlightBrief() {
  return <section className="editorial-section flight-brief" id="repules"><div className="section-kicker">Újramérve {priceCheck.checkedOn}</div><h2>A shenzheni kapu kiesett – három másik maradt</h2><div className="flight-grid">
    <article><span className="airport">SZX</span><h3>Shenzhen – nem eladó</h3><p>A Hainan HU 761/762 a menetrendben szerepel, de október 16-ra és a teljes okt. 26–31. ablakra egyetlen jegyárus sem ad árat. Az eddigi terv alapja ezzel megszűnt.</p><SourceLink source={sources.flightSZXBUD} /></article>
    <article className="recommended"><span className="badge">A LEGKISEBB VÁLTOZTATÁS</span><span className="airport">CAN</span><h3>Guangzhou, oda-vissza</h3><p>China Southern CZ 650 okt. 17-én 12:45 → 05:30+1 (10 óra 45 perc) és CZ 649 okt. 29-én 01:30 → 07:10. <strong>{grouped(3204)} € négy főre</strong>, mindkét irány közvetlen. Shenzhen innen 30–75 perc gyorsvasút, tehát a lenti hét útvonal érintetlenül működik. Kedden, csütörtökön és szombaton jár.</p><SourceLink source={sources.flightCANBUD} /></article>
    <article><span className="airport">PEK</span><h3>Peking – a legrövidebb és a legkényelmesebb</h3><p>Air China naponta, oda 9 óra 10 perc, vissza 14:00 → 17:35 – <strong>az egyetlen nappali hazaút</strong>. Egy irányba {grouped(2431)} € (okt. 16.), vissza {grouped(1306)} € (okt. 29.). Nagy Fal, Tiltott Város, és innen érhetők el a buddhista sziklatemplomok is.</p><SourceLink source={{ label: "Trip.com BUD–PEK", url: "https://us.trip.com/flights/budapest-to-beijing/tickets-bud-pek" }} /></article>
    <article><span className="airport">PVG</span><h3>Shanghai – a legolcsóbb</h3><p>Shanghai Airlines naponta, 11 óra 5 perc. Egy irányba {grouped(2090)} €, oda-vissza {grouped(2884)} € négy főre. Figyelem: a Google ezt a járatot egyetlen dátumon sem árazza – csak a Trip.comon és a China Eastern oldalán látszik.</p><SourceLink source={{ label: "Trip.com BUD–PVG", url: "https://us.trip.com/flights/budapest-to-shanghai/tickets-bud-sha" }} /></article>
  </div><div className="notice"><strong>A lenti hét útvonal a guangzhoui keretre van átszámolva.</strong> Ha az északi ív – Peking, Xi’an, Longmen buddha-barlangtemplomok – is szóba jön, az <a href="./repuloarak/"><strong>repülőárak oldalon</strong></a> ott a teljes összevetés: nyolc közvetlen architektúra, {grouped(2884)} € és {grouped(4151)} € között.</div></section>;
}
